### PR TITLE
Writing Quickstart/Tutorial Guide #161

### PR DESCRIPTION
**Pull request by christian7974**
Started writing the Quickstart Guide/Tutorial for Asteroid, for the #161 issue.

### CODE REVIEW

**Comment by olwmc** [comment]
Hi! Before anything, please change the branch you're merging into to be the dev branch. Then I'll take a look

**Comment by christian7974** [comment]
No problem, sorry about that @olwmc

**Review by lutzhamel — COMMENTED** [review]
Hi Christian,

That looks pretty good.  Here are a couple of initial comments:

* I think there is a typo in your ML function, I think it should read
   ```
   fun f (0) = "zero"
     | f (x) = "not zero";
   ```
* It might be best to stick to the same example for all languages and I would probably not introduce first-class conditional patterns in the fifth paragraph of a quickstart tutorial 🙂.  I would probably just translate the ML example into Asteroid and discuss that Asteroid implements functional style pattern matching.  Then perhaps discuss the factorial function with first-class conditional patterns and the end of section of pattern matching.
* In your OO example for C++ you are building the object on the stack.  Most folks prefer to build their objects on the heap using the `new` keyword.  Also, that way you can create a constructor that works similar to the default constructor in Asteroid. That means both the C++ and the Asteroid programs will look pretty similar giving the reader an "in".
* So Asteroid does not implement object-orientation but object-based programming - Asteroid does not have inheritance very similar to Rust and Go.  That might be worthwhile mentioning.
* I think you will need to discuss the `let` statement because it is not an assignment statement but a pattern match statement where things like this,
   ```
   let 1 = 1.
   ```
  are perfectly legal.

**Comment by christian7974** [comment]
No problem, I can take a look at those.

**Comment by lutzhamel** [comment]
Great, thanks.  I'm wondering if it would make sense to fold some of the material from our Asteroid homepage into the quickstart doc,
[https://asteroid-lang.org/](https://asteroid-lang.org/)

That page serves like an overview of features but it is very terse...

**Comment by christian7974** [comment]
I did a couple of the things you said and I was thinking the same thing. I feel like that page throws you in to the language (no baby steps). Something I was thinking about in the future was to write a more in-depth intro (as if you were learning about the language in a class at school) so that it would be easier to get started.

**Comment by lutzhamel** [comment]
@christian7974 Thanks for the update.  It looks like a great start. I like the idea of a C++ quick start tutorial.  I started to do some editing to highlight some of the issue a bit more.  I will be giving it a deeper read throughout the day today...

**Comment by olwmc** [comment]
Quick note, I haven't read through the guide yet, just a meta question. Do we want that `.vscode/` folder? It should probably be added to `.gitignore` :)

**Comment by lutzhamel** [comment]
That should definitely go into .gitignore, I'm glad you caught that!

I'm still working on a new draft of the qstart guide...I will have something later that folks can take a peek at...

**Comment by lutzhamel** [comment]
@christian7974 take a peek at my edits.  Feel free to add or rewrite.  Thanks again for getting this started.

@olwmc I'd be interested to hear if you think that this provides a reasonable quick start for C++ programmer or if there are things that we should add.  Whatever we decide we should try to keep the overlap with the User Guide to a minimum...

**Comment by christian7974** [comment]
It looks good; I fixed some minor spelling/grammatical errors within but I think it looks great. Is there something else I can add/change to it?
I also added the ```.vscode/``` directory to the ```.gitignore```.
Also, I noticed that in Asteroid, you can use the @ to "```access substructures of objects with the access operator @```", but what does it mean when it is in front of the println (something like ``` io @println "Hello, World!"```, possibly something little I can add to the quickstart guide)?

**Comment by lutzhamel** [comment]
@christian7974 Interesting observation.  I don't think we ever spell out explicitly that in Asteroid 1.0 system modules are actually objects and to access the functions of a module you have to use the access operator `@`.  So,
```
load system io.
```
loads module/object `io` and to access a function of that module you have to do the following,
```
io @println "Hello, World!".
```
This might be something useful to put into the qstart guide and it is certainly something we should put into the User Guide where we discuss modules.

**Comment by christian7974** [comment]
I can talk about the @ and modules more in the User Guide, but I do not know if I should edit the .txt version or the .rst version of it.

**Comment by lutzhamel** [comment]
@christian7974 sounds good.  You have to edit the txt file and then follow the instructions at the top of the txt file in order to generate the rst file.

If you include code then that code has to live in the ug-programs folder under test-suites.  Look for examples in the user guide doc on how to include the code into the doc itself.  By doing it this way the code snippets are guaranteed to not go stale since the test suite is run on every pull request and the if a test fails the pull request is rejected.

**Comment by lutzhamel** [comment]
@christian7974 feel free to merge this PR.  Just one quick comment...perhaps at the end of the doc you could say something like "for more details please see the Asteroid user and reference guides"...thanks for taking on this project...now I am wondering if we should write something like this for Python programmers 🙂

**Review by TimColaneri — APPROVED** [review]
Sorry about taking forever with this review.

This all looks great to me.

**Pull request merged**
