### PR TITLE
Implemented math @round

### PR DESCRIPTION
**Pull request by ijchen**
Implemented #262.  Tests are currently not passing in general due to breaking `dev-2.0.1` changes, but as far as I can tell sorting through the wall of failures, the `round` test (`test083.ast`) passes. Please let me know if there are any improvements you would suggest, and I'd be happy to make them.

I'm especially interested in feedback on the documentation, because it's obviously important that the structure and phrasing of documentation is consistent, and I'd rather get the documentation right when adding it instead of making later changes to existing published documentation.

### CODE REVIEW

**Comment by lutzhamel** [comment]
@ijchen Could you push your branch into the repo so I can check it out. We usually name the branches by the issue # that they address.  I just checked out dev-2.0.1 and it passes all test suites so I am not quite sure what's going on.

**Comment by ijchen** [comment]
Yes, I'll push it now. Also good to know about the convention for branch names, I'll adhere to that in the future.

**Comment by ijchen** [comment]
It looks like it's already available on my fork of asteroid: https://github.com/ijchen/asteroid/tree/dev-2.0.1

Worth noting, I'm currently looking into an unrelated but suspicious issue locally, which makes me think there may be something wrong with my setup. It's possible all the tests should pass, I'll update if I find anything.

**Comment by lutzhamel** [comment]
Hmmm, I just checked out your dev-2.0.1 branch and successfully ran all the tests including yours. So I'm not quite sure what's going on.  Do have an old copy of Asteroid installed somewhere?  Does your PYTHONPATH happen to point to it?  How about pip?  Did you uninstall all Asteroid installations?  Can't think of anything else right now.

BTW, the general regression test suite is regression-tests, could you move your test into that testsuite? 

I think we as a team have some work to do in terms of providing docs for the onboarding process 🤔

**Comment by lutzhamel** [comment]
@ijchen Could you send me a screenshot of the error messages the testsuites produce when you run them?

**Comment by ijchen** [comment]
Sure, I'll send that over on Slack

**Review by lutzhamel — APPROVED** [review]

**Pull request merged**
