### PR TITLE
fixes issue #149

### PR DESCRIPTION
**Pull request by lutzhamel**
Introduced the `token_value` table which is essentially a reverse `token_spec` table that given a token type produces a readable representation of the associated token value.  This allows us to improve the error messages generated by the frontend, e.g.,
```
Error: parse.ast: 2: expected RPAREN found COMMA.
```
to
```
Error: parse.ast: 2: expected ')' found ','
```

### CODE REVIEW

**Review by olwmc — CHANGES_REQUESTED** [review]
Everything looks great! The only thing I think we should think more about is the changes made to `interp.py`.

Originally, I had included:
```python
if not exceptions:
    sys.exit(1)
```
in each exception to allow the REPL to work. This is because the REPL catches these exceptions and uses them to A) do multi-line statements or B) show exceptions without terminating the REPL session. As of right now, this change breaks the REPL. What's the rational for removing the `exceptions` check? We might be able to work around it.

**Comment by olwmc** [comment]
I agree that overloading one parameter, `exceptions`, is not ideal.

**Review by olwmc — COMMENTED** [review]
Looks great!!!!!!

**Review by olwmc — APPROVED** [review]

**Comment by olwmc** [comment]
One second. The REPL still seems to be broken. Let me try and figure this out 🤔

**Comment by olwmc** [comment]
Okay, I think I have it figured out. Let me do a little testing to get a better idea, then I'll write back.

**Comment by olwmc** [comment]
Two main issues that are causing the REPL to break:

**1.**
In `lex.py` there is this line in `match`:
```python
raise ExpectationError(found=token_lookup(self.curr_token.type),
    expected=token_lookup(token_type))
```
This seems to break when the expected token is 'EOF'. Adding `{'EOF':'EOF'}` to `token_values` in its initializer seems to solve this. 

**2.**
The REPL requires `ExpectationError` to be caught when present. To do this, we need to rethrow it in `interp()`. This was originally accomplished by the `except Exception as e:` clause in `interp()` but, in an otherwhise correct attempt to standardize Exception handling, is now no longer thrown. Changing the `ExpectationError` handler in `interp()` to look almost identical to the `Exception` one fixes this. I.E.:
```python
    # Expectation Error is used by the REPL, so, like exceptions,
    # we re throw it
    except ExpectationError as e:
        if exceptions:
            raise e
        else:
            module, lineno = state.lineinfo
            print("Error: {}: {}: {}".format(module, lineno, e.value))
            # needed for REPL
            if not exceptions:
                sys.exit(1)
```

After testing, these changes seem to work correctly. I have the fixes working locally and can push to this branch if requested!

**Review by olwmc — CHANGES_REQUESTED** [review]
Quick comments about REPL

**Comment by lutzhamel** [comment]
@olwmc I have push your requested changes into the PR.  Please take another peek. Thanks!

**Review by olwmc — APPROVED** [review]
Fantastic!!!

**Pull request merged**
