### PR TITLE
Issue 182

### PR DESCRIPTION
**Pull request by lutzhamel**
The -F flag puts the Asteroid interpreter into a purely functional mode where the parser will reject all procedural syntactic structures like for loops and if statements.  System modules are not affected by this flag so the user can still use the system modules written in procedural Asteroid in the purely functional program.

### CODE REVIEW

**Review by olwmc — APPROVED** [review]
Looks good! Nice and simple solution

**Comment by olwmc** [comment]
Working on fixing the docs issue

**Comment by olwmc** [comment]
Things should actually be fine. That failed test seems to be an artifact from when we made the change in the documentation generation script to go from "dev-1.0" to "dev-1.1.0"

**Review by TimColaneri — APPROVED** [review]
Looks good to me.

**Pull request merged**
