### PR TITLE
Ticket #122

### PR DESCRIPTION
**Pull request by olwmc**
This PR solves issue #122 by 

A) Disallowing negative step values for list comprehensions

B) Inferring step direction by range start and end

Because I'm using python ranges to accomplish this functionality I had to do a little bit of work to get the offset correct. Regardless, this should work as intended.

__Please break this PR if you can, I'd love to improve it.__

### CODE REVIEW

**Review by lutzhamel — COMMENTED** [review]
did we want to change the syntax from `step` to `stride` in order to highlight the fact this is not your Python step but something else?

**Comment by olwmc** [comment]
Oh I'd be happy to do that in this PR. I was going to open a syntax change issue after this was merged. I'll get on that tomorrow morning.

**Comment by lutzhamel** [comment]
I think implementing `stride` as part of #122 makes sense given that the discussion on `stride` happened in issue #122.

**Comment by lutzhamel** [comment]
I changed target of the pull request from 'master' to 'dev-1.0.0'

**Comment by olwmc** [comment]
So the only thing I have left to fix are in `User Guide.rst`, `User Guide.txt`,  `Reference Guide.rst`, `Reference Guide.txt` and `Asteroid in Action.rst`.

I'm not super sure how these files work since I believe they're machine generated. How should I go about fixing the instances here? 

Note: I found out which files still have a step->stride fix needed by grepping the repo for 'step' and looking through each one to see if it is the 'step' we're actually talking about

**Comment by olwmc** [comment]
Figured it out! This should be good to go.

**Comment by olwmc** [comment]
Hold on. Sorry. There's some weird issue going on with the documentation generation.

**Review by lutzhamel — APPROVED** [review]
Looking good! Did you get a chance to take a peek at the asteroid/programs folder?  I have no idea if there are programs in there that need a fix for the new syntax...

feel free to merge your PR and any time!  Excellent Job!

**Comment by olwmc** [comment]
Yes I checked the whole tree of files. Grep has a `-r` directive but just to make sure I went through each folder/subfolder.

**Pull request merged**
